<?php

$this->title = "Delete album";
$this->headTitle($this->title);
?>

<p>
    Are you sure that you want to <strong>delete
		<?php echo $this->escape($this->album['title']); ?>
        by
		<?php echo $this->escape($this->album['artist']); ?>?</strong>
</p>
<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->album['id'];?>"/>
        <input type="submit" name="del" value="No"/>
        <input type="submit" name="del" value="Yes"/>
    </div>
</form>