<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'add'));?>"><button>Add new album</button></a></p>
<table>
    <tr>
        <th>Artist</th>
        <th>Title</th>
        <th>Action</th>
    </tr>
    <?php
//    echo "<pre>";
//    print_r($this->albums);
//    echo "</pre>";
    ?>
	<?php foreach($this->albums as $album) : ?>
        <tr>
            <td><?php echo $this->escape($album->artist);?></td>
            <td><?php echo $this->escape($album->title);?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$album->id));?>"><button>Edit</button></a>
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$album->id));?>"><button>Delete</button></a>
            </td>
        </tr>
	<?php endforeach; ?>
</table>